<?php

/**
 * @file
 * Functions for the contactmap module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implementation of contactmap_help().
 */
function contactmap_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.contactmap':
      $output = '<p>' . t('This module places a Contact map and address with a phone number (click-to-open) to the user.
User can drag and place the object in your website of the screen.
This module is very useful for a lead generation website contact for a user connection, it available on your all web page it will allow them easily to contact.') . '</p>';
      $output .= '<h3>' . t('How to use the plugin') . '</h3>';
      $output .= t('<strong>IMPORTANT:</strong> The first field in order of appearance will be the one used as the "lat and lon" of the web to contact.') . '<br />';
      $output .= '<h4>' . t('Your Contactmap must meet these requirements:') . '</h4>';
      $output .= '<ul>';
      $output .= '<li>' . t('<em>phone</em> must be set to <em>Fields</em>.') . '</li>';
      $output .= '</ul>';
      $output .= '<h4>' . t('Choose <em>Contact Map</em> in the <em>Style</em> dialog within your view, which will prompt you to configure the settings.') . '</h4>';
      return $output;
  }
}

/**
 * Implements hook_preprocess_page().
 */
function contactmap_preprocess_page(&$variables) {
  $config = \Drupal::config('contactmap.settings');
  $theme_selected = $config->get('contactmapThemename');
  $active_theme = \Drupal::service('theme.manager')->getActiveTheme()->getName();
  // If condition for the frontend active theme showing this functionality.
  if (array_keys($theme_selected, $active_theme)) {
    $variables['#attached']['library'][] = 'contactmap/contactmap';
    // Google map API key get values.
    $variables['#attached']['drupalSettings']['mapGooglekey'] = $config->get('mapGooglekey');
    // Callus button get setting values.
    $variables['#attached']['drupalSettings']['mapPhoneNumber'] = $config->get('mapPhoneNumber');
    $variables['#attached']['drupalSettings']['mapAddressContact'] = $config->get('mapAddressContact');
    // Social button getting values.
    $variables['#attached']['drupalSettings']['mapLatitude'] = $config->get('mapLatitude');
    $variables['#attached']['drupalSettings']['mapLongitude'] = $config->get('mapLongitude');
    // Theme getting value.
    $variables['#attached']['drupalSettings']['contactmapThemename'] = $config->get('contactmapThemename');
  }
}
